apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-frontend
  labels:
    app: simple-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-frontend
  template:
    metadata:
      labels:
        app: simple-frontend
    spec:
      containers:
      - name: simple-frontend
        image: <your-ecr-url>/simple-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: simple-frontend-service
  labels:
    app: simple-frontend
spec:
  selector:
    app: simple-frontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
